# Generated by Django 5.2.16 on 2026-07-30 08:45

import django.db.models.deletion
from django.db import migrations, models


def backfill_active_versions(apps, schema_editor):
    Function = apps.get_model("functions", "Function")
    FunctionVersion = apps.get_model("functions", "FunctionVersion")
    for function in Function.objects.filter(active_version__isnull=True):
        version = (
            FunctionVersion.objects.filter(
                function=function,
                build_status="built",
            )
            .exclude(image_ref="")
            .order_by("-created_at", "-id")
            .first()
        )
        if version is not None:
            function.active_version_id = version.id
            function.save(update_fields=["active_version"])


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0008_input_total_limit_and_output_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='function',
            name='active_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='functions.functionversion'),
        ),
        migrations.RunPython(backfill_active_versions, migrations.RunPython.noop),
    ]
