# Generated by Django 5.2.16 on 2026-07-30 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0009_function_active_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunctionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_ref', models.CharField(max_length=500, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('candidate', 'Candidate'), ('pending_delete', 'Pending delete'), ('deleted', 'Deleted'), ('delete_failed', 'Delete failed')], db_index=True, default='candidate', max_length=30)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('delete_after', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('delete_attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('function', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='functions.function')),
                ('function_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='functions.functionversion')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['function', 'status'], name='functions_f_functio_c9342d_idx'), models.Index(fields=['status', 'delete_after'], name='functions_f_status_fa222e_idx')],
            },
        ),
    ]
