# Generated by Django 5.2.16 on 2026-07-30 09:12

from django.db import migrations


def backfill_function_images(apps, schema_editor):
    Function = apps.get_model("functions", "Function")
    FunctionImage = apps.get_model("functions", "FunctionImage")
    FunctionVersion = apps.get_model("functions", "FunctionVersion")

    active_by_function = {
        function.id: function.active_version_id
        for function in Function.objects.exclude(active_version__isnull=True)
    }
    for version in FunctionVersion.objects.exclude(image_ref="").iterator():
        is_active = active_by_function.get(version.function_id) == version.id
        status = "active" if is_active else "pending_delete"
        reason = "backfilled active build" if is_active else "backfilled superseded build"
        FunctionImage.objects.get_or_create(
            image_ref=version.image_ref,
            defaults={
                "function_id": version.function_id,
                "function_version_id": version.id,
                "status": status,
                "reason": reason,
            },
        )


def reverse_backfill_function_images(apps, schema_editor):
    FunctionImage = apps.get_model("functions", "FunctionImage")
    FunctionImage.objects.filter(
        reason__in=["backfilled active build", "backfilled superseded build"],
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0010_functionimage'),
    ]

    operations = [
        migrations.RunPython(
            backfill_function_images,
            reverse_backfill_function_images,
        ),
    ]
