# Generated by Django 5.2.16 on 2026-07-30 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0011_backfill_function_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='functioninvoketoken',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
