# Generated by Django 5.2.15 on 2026-07-28 10:28

import apps.invocations.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invocations', '0004_staged_completions'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvocationLogArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream', models.CharField(choices=[('stdout', 'Stdout'), ('stderr', 'Stderr')], max_length=20)),
                ('status', models.CharField(choices=[('staged', 'Staged'), ('committed', 'Committed'), ('expired', 'Expired')], db_index=True, default='committed', max_length=20)),
                ('file', models.FileField(max_length=500, upload_to=apps.invocations.models.invocation_log_upload_to)),
                ('safe_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(default='text/plain', max_length=255)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('preview', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_artifacts', to='invocations.invocation')),
                ('staged_completion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='log_artifacts', to='invocations.invocationstagedcompletion')),
            ],
            options={
                'ordering': ['stream', 'created_at'],
                'indexes': [models.Index(fields=['invocation', 'stream'], name='invocations_invocat_6d7397_idx'), models.Index(fields=['staged_completion', 'stream'], name='invocations_staged__21e202_idx')],
            },
        ),
    ]
